//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeritabanıEntities1 : DbContext
    {
        public VeritabanıEntities1()
            : base("name=VeritabanıEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FILMLER> FILMLER { get; set; }
        public virtual DbSet<KATEGORILER> KATEGORILER { get; set; }
        public virtual DbSet<KULLANICILAR> KULLANICILAR { get; set; }
        public virtual DbSet<YORUMLAR> YORUMLAR { get; set; }
    }
}
