//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class FILMLER
    {
        public int FILMID { get; set; }
        public Nullable<int> KATEGORIID { get; set; }
        public string FILMAD { get; set; }
        public Nullable<System.DateTime> FILMYIL { get; set; }
        public Nullable<byte> FILMPUAN { get; set; }
        public string FILMOZET { get; set; }
        public string FILMFOTO { get; set; }


        public virtual KATEGORILER KATEGORILER { get; set; }
    }
}
