//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILMLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILMLER()
        {
            this.YORUMLAR = new HashSet<YORUMLAR>();
        }
    
        public int FILMID { get; set; }
        public Nullable<int> KATEGORIID { get; set; }
        public string FILMAD { get; set; }
        public Nullable<System.DateTime> FILMYIL { get; set; }
        public Nullable<byte> FILMPUAN { get; set; }
        public string FILMOZET { get; set; }
        public string FILMFOTO { get; set; }
    
        public virtual KATEGORILER KATEGORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YORUMLAR> YORUMLAR { get; set; }
    }
}
