//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class YORUMLAR
    {
        public int YORUMID { get; set; }
        public Nullable<int> KULLANICIID { get; set; }
        public string KULLANICIYORUM { get; set; }
        public Nullable<int> YORUMFILMID { get; set; }

        public Nullable<byte> YORUMPUAN { get; set; }
    
        public virtual FILMLER FILMLER { get; set; }
        public virtual KULLANICILAR KULLANICILAR { get; set; }
    }
}
