//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebProje.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 ÖFKELİ ADAM.
        /// </summary>
        public static string _12ofkeliadam {
            get {
                return ResourceManager.GetString("12ofkeliadam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 Öfkeli Adam, cinayetle suçlanan bir genç ile ilgili karar vermekle yükümlü 12 jüri üyesinin karar verme sürecini konu ediyor. Latin Amerikalı bir genç adam, babasını öldürdüğü gerekçesiyle cinayetle suçlanır. Sanığın kaybettiğini söylediği bir bıçak ise cinayetin işlendiği odada bulunmuştur, gencin mahkemeye sunduğu savunma zayıftır ve olan biteni duyduklarını söyleyen pek çok tanık vardır....
        /// </summary>
        public static string _12ofkeliadamtanitim {
            get {
                return ResourceManager.GetString("12ofkeliadamtanitim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANA SAYFA.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ★BU AY EN ÇOK İZLENEN 3 FİLM★.
        /// </summary>
        public static string ayineniyiuclusu {
            get {
                return ResourceManager.GetString("ayineniyiuclusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇIKIŞ YAP.
        /// </summary>
        public static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DİL SEÇİNİZ.
        /// </summary>
        public static string dilsecimi {
            get {
                return ResourceManager.GetString("dilsecimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDİTÖRÜN EN İYİLERİ.
        /// </summary>
        public static string editörüneniyileri {
            get {
                return ResourceManager.GetString("editörüneniyileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ★EDİTÖRÜN EN İYİ ÜÇLÜSÜ★.
        /// </summary>
        public static string editoruneniyiuclusu {
            get {
                return ResourceManager.GetString("editoruneniyiuclusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKLE.
        /// </summary>
        public static string ekle {
            get {
                return ResourceManager.GetString("ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ★EN İYİLER SIRALAMASI★.
        /// </summary>
        public static string eniyilersiralamasi {
            get {
                return ResourceManager.GetString("eniyilersiralamasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FİLMLER.
        /// </summary>
        public static string filmler {
            get {
                return ResourceManager.GetString("filmler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÜNCELLE.
        /// </summary>
        public static string guncelle {
            get {
                return ResourceManager.GetString("guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKINDA.
        /// </summary>
        public static string hakkinda {
            get {
                return ResourceManager.GetString("hakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Hakları Saklıdır.
        /// </summary>
        public static string haklar {
            get {
                return ResourceManager.GetString("haklar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIZLI LİNKLER.
        /// </summary>
        public static string hizlilink {
            get {
                return ResourceManager.GetString("hizlilink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş Geldin.
        /// </summary>
        public static string hosgeldin {
            get {
                return ResourceManager.GetString("hosgeldin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KATEGORİLER.
        /// </summary>
        public static string kategoriler {
            get {
                return ResourceManager.GetString("kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string kaydet {
            get {
                return ResourceManager.GetString("kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİL.
        /// </summary>
        public static string sil {
            get {
                return ResourceManager.GetString("sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYANIŞ.
        /// </summary>
        public static string uyanis {
            get {
                return ResourceManager.GetString("uyanis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oliver Sacks’ın kendi hayatını kaleme aldığı aynı isimli romandan sinemaya uyarlanan film, ömrünü bilime adayan asosyal bir doktorun, icat ettiği bir ilaç sayesinde değiştirdiği yaşamları anlatır. Nörolog Malcolm Sayer, yeni çalışmaya başladığı bir hastanede, daha önce görmediği tarzda bir hastalığa sahip bir grup hastayla karşılaşır. Bu insanlar uzun yıllardır hareket etmeden yatağa bağlı bir şekilde uyku modundadırlar....
        /// </summary>
        public static string uyanistanitim {
            get {
                return ResourceManager.GetString("uyanistanitim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEŞİL YOL.
        /// </summary>
        public static string yesilyol {
            get {
                return ResourceManager.GetString("yesilyol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeşil Yol, bir hapishane görevlisi ile bir mahkumun öyküsünü anlatıyor. Paul Edgecomb&apos;un hapishanedeki görevi, idama mahkum edilen mahkumları son yolculuklarına uğurlamaktır. Çalıştığı yıllar içerisinde yüzlerce mahkumu idam etmiştir. Bir gün John Coffey isimli korkutucu görünümlü bir adamla tanışır. Ancak Coffey&apos;in bu ürkütücü görünümünün altında oldukça saf bir ruh yatmaktadır. Coffey, iki küçük kız çocuğunun katil davasında yargılanmaktadır....
        /// </summary>
        public static string yesilyoltanitim {
            get {
                return ResourceManager.GetString("yesilyoltanitim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YORUMLARA GİT.
        /// </summary>
        public static string yorumgoruntule {
            get {
                return ResourceManager.GetString("yorumgoruntule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YORUM YAP.
        /// </summary>
        public static string yorumyap {
            get {
                return ResourceManager.GetString("yorumyap", resourceCulture);
            }
        }
    }
}
